# Generated by Django 5.0.8 on 2024-08-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_owner_salespipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(choices=[('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('master_bedroom', 'Master Bedroom'), ('guest_bedroom', 'Guest Bedroom'), ('bathroom', 'Bathroom'), ('dining_room', 'Dining Room'), ('office', 'Office'), ('garage', 'Garage'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.salespipeline')),
            ],
        ),
    ]
