# Generated by Django 5.0.8 on 2024-08-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_campaign_lead_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='normal_price',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('master_bedroom', 'Master Bedroom'), ('guest_bedroom', 'Guest Bedroom'), ('bathroom', 'Bathroom'), ('dining_room', 'Dining Room'), ('office', 'Office'), ('garage', 'Garage'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
