# Generated by Django 5.0.8 on 2024-08-10 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_price_product_normal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.salespipeline'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
