# Generated by Django 5.0.8 on 2024-08-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_product_pipeline_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='https://placeholder.url', max_length=500),
        ),
    ]
